
#FROM openjdk:8
FROM openjdk:8-jre

ENV LOGSTASH_HOME /usr/local/logstash
ENV WORKING_DIR /usr/local/scripts
ADD entrypoint-logstash.sh /usr/local/scripts/
ADD logstash.conf /usr/local/scripts/
RUN mkdir -p $LOGSTASH_HOME/logstash-5.4.0

RUN apt-get update && apt-get install -y procps

# install logstash
	RUN wget https://artifacts.elastic.co/downloads/logstash/logstash-5.4.0.tar.gz && \
		tar -xvf logstash-5.4.0.tar.gz && \
		mv logstash-5.4.0 $LOGSTASH_HOME


WORKDIR $WORKING_DIR
 
RUN chmod 755 /usr/local/scripts/entrypoint-logstash.sh

ENTRYPOINT ["/usr/local/scripts/entrypoint-logstash.sh"]