FROM openjdk:8-jre

ENV KAFKA_HOME /usr/local/kafka

RUN mkdir -p /usr/local/scripts

ENV WORKING_DIR /usr/local/scripts
 
# install java + others
#RUN apt-get update && apt-get install -y \
#  wget \
#  openjdk-8-jdk
 
# install kafka
	RUN wget https://archive.apache.org/dist/kafka/0.10.2.0/kafka_2.10-0.10.2.0.tgz && \
		tar -xvf kafka_2.10-0.10.2.0.tgz && \
		mv kafka_2.10-0.10.2.0 $KAFKA_HOME

EXPOSE 2181
EXPOSE 9092

ADD entrypoint-kafka.sh $WORKING_DIR
ADD server.properties $WORKING_DIR
 
RUN chmod 755 /usr/local/scripts/entrypoint-kafka.sh

WORKDIR $WORKING_DIR
 

ENTRYPOINT ["/usr/local/scripts/entrypoint-kafka.sh"]